# Generated by Django 3.0.2 on 2020-01-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'sativa'), (1, 'indica'), (2, 'hybrid')], null=True)),
                ('thc', models.CharField(blank=True, max_length=255, null=True)),
                ('cbd', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.IntegerField(blank=True, choices=[(0, 'easy'), (1, 'moderate'), (2, 'difficult')], null=True)),
                ('height', models.IntegerField(blank=True, choices=[(0, '< 30'), (1, '30 - 78'), (2, '> 78')], null=True)),
                ('crop', models.IntegerField(blank=True, choices=[(0, '0.5 - 1'), (1, '1 - 3'), (2, '3 - 6')], null=True)),
                ('flowering', models.IntegerField(blank=True, choices=[(0, '7 - 9'), (1, '10 - 12'), (2, '> 12')], null=True)),
                ('parents', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
