# Generated by Django 2.2.6 on 2020-02-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strain", name="short", field=models.CharField(max_length=50),
        ),
    ]
