# Generated by Django 2.2.6 on 2020-02-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0003_strain_icon"),
    ]

    operations = [
        migrations.RemoveField(model_name="strain", name="short",),
    ]
