# Generated by Django 2.2.6 on 2020-02-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0005_auto_20200209_1502"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="strain",
            options={"verbose_name": "Сорт", "verbose_name_plural": "Сорта"},
        ),
        migrations.AlterField(
            model_name="strain",
            name="cbd",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="КБД"
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="crop",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "0.5 - 1"), (1, "1 - 3"), (2, "3 - 6")],
                null=True,
                verbose_name="Урожайность",
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="difficulty",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Легкая"), (1, "Средняя"), (2, "Высокая")],
                null=True,
                verbose_name="Сложность выращивания",
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="flowering",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "7 - 9"), (1, "10 - 12"), (2, "> 12")],
                null=True,
                verbose_name="Время цветения",
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="height",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "< 30"), (1, "30 - 78"), (2, "> 78")],
                null=True,
                verbose_name="Высота растения",
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="icon",
            field=models.CharField(default="🌿", max_length=50, verbose_name="Иконка"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название сорта"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="parents",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Генетика"
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="slug",
            field=models.SlugField(verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="thc",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ТГК"
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Сатива"), (1, "Индика"), (2, "Гибрид")],
                null=True,
                verbose_name="Тип",
            ),
        ),
    ]
