# Generated by Django 2.2.6 on 2020-02-09 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
            ],
            options={
                "verbose_name": "Варианты доставки",
                "verbose_name_plural": "Варианты доставки",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
            ],
            options={
                "verbose_name": "Варианты оплаты",
                "verbose_name_plural": "Варианты оплаты",
            },
        ),
        migrations.CreateModel(
            name="ProductOptionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Тип опции")),
            ],
            options={
                "verbose_name": "Тип опции продукта",
                "verbose_name_plural": "Типы опций продукта",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "delivery_options",
                    models.ManyToManyField(
                        blank=True,
                        to="products.Delivery",
                        verbose_name="Варианты доставки",
                    ),
                ),
                (
                    "payment_options",
                    models.ManyToManyField(
                        blank=True,
                        to="products.Payment",
                        verbose_name="Варианты оплаты",
                    ),
                ),
            ],
            options={"verbose_name": "Магазин", "verbose_name_plural": "Магазины",},
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Значение")),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.ProductOptionType",
                        verbose_name="Опция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция продукта",
                "verbose_name_plural": "Опции продукта",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название товара"),
                ),
                (
                    "producer",
                    models.CharField(max_length=255, verbose_name="Производитель"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Цена"
                    ),
                ),
                (
                    "package",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Упаковка"
                    ),
                ),
                ("url", models.URLField(verbose_name="Ссылка на страницу магазина")),
                (
                    "product_options",
                    models.ManyToManyField(
                        blank=True,
                        to="products.ProductOption",
                        verbose_name="Опции товара",
                    ),
                ),
                (
                    "shop",
                    models.ManyToManyField(
                        blank=True, to="products.Shop", verbose_name="Магазин"
                    ),
                ),
            ],
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары",},
        ),
    ]
